### ISSUE TITLE
Set up GitHub Actions

### ISSUE THREAD

**Issue by mrombout** [mrombout/Spiner#59]
Let's get some of that GitHub Action!

**Comment by mrombout** [comment]
With the default set-up JavaFX is not supported, see https://github.com/actions/setup-java/issues/18.

- I could ditch JavaFX because the web version is going to be the main one anyway.
- I could see if I can install a proper OracleJDK 8 with that (which should have JavaFX)
- I suppose I could fork that action and add JavaFX support myself.

**Comment by airsquared** [comment]
@mrombout I created a PR to setup-java (actions/setup-java#19) that adds support for JavaFX, so you can use that if it's merged(or you can use my fork directly).
